spring:
  application:
    name: ThinkGearReaderFX
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: waves
    template:
      default-topic: raw


info:
  # static properties
  app:
    name: ${spring.application.name}
    description: --

logging:
  level:
    root: info
    com.globant.brainwaves.adapter: info
